const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

const CLEAR_ERRORS = "CLEAR_ERRORS";

module.exports = {
  ALL_PRODUCTS_FAIL,
  ALL_PRODUCTS_REQUEST,
  ALL_PRODUCTS_SUCCESS,
  CLEAR_ERRORS,
  //
  PRODUCT_DETAILS_FAIL,
  PRODUCT_DETAILS_REQUEST,
  PRODUCT_DETAILS_SUCCESS,
};
